using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Resources;

[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Types.XmlResourceMapChunk.#ParseBody(Microsoft.Arcadia.Marketplace.Decoder.Portable.Common.StreamDecoder)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Decoder.XmlDecoder.#XmlChunk")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Decoder.XmlChunkDecoder.#Decode(Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Types.XmlChunk)")]
[assembly: AssemblyTitle("Portable")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Resources.Decoder.ResourcesDecoder.#TableChunk")]
[assembly: AssemblyCompany("")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Types.XmlChunk.#ParseBody(Microsoft.Arcadia.Marketplace.Decoder.Portable.Common.StreamDecoder)")]
[assembly: AssemblyInformationalVersion("1.0.0.9081")]
[assembly: AssemblyFileVersion("1.0.0.9081")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2243:AttributeStringLiteralsShouldParseCorrectly", Justification = "By Design - we store the Arcadia build number in the InformationalVersion")]
[assembly: AssemblyProduct("Portable")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "namespace", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Common")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Common.Chunk.#Parse(Microsoft.Arcadia.Marketplace.Decoder.Portable.Common.StreamDecoder)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Manifest.Decoder.ManifestDecoder.#XmlChunk")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Resources.Decoder.ResourcesDecoder.#ToString()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Log statement", MessageId = "Microsoft.Arcadia.Marketplace.Utils.Log.LoggerCore.Log(System.String)", Scope = "member", Target = "Microsoft.Arcadia.Marketplace.Decoder.Portable.Resources.Decoder.ResourcesHelper.#GetResourceGroups(Microsoft.Arcadia.Marketplace.Decoder.Portable.Resources.Types.TableChunk)")]
[assembly: AssemblyVersion("0.0.0.0")]
